Add RHEL `V6` container support [DI-375]
hazelcast/hazelcast-docker pull request #844
Opened 2024-12-10 17:09 UTC by JackPGreen

Re-instates the version selection logic removed in https://github.com/hazelcast/hazelcast-docker/pull/811 to support `V6` RHEL.

Fixes: [DI-375](https://hazelcast.atlassian.net/browse/DI-375)

[DI-319]: https://hazelcast.atlassian.net/browse/DI-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DI-375]: https://hazelcast.atlassian.net/browse/DI-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-11 13:38 UTC, nishaatr requested changes

2024-12-11 14:12 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +      - name: Set scan registry secrets
They were hardcoded `env` variables.

2024-12-11 15:00 UTC, nishaatr approved these changes

2024-12-19 11:39 UTC, ldziedziul approved these changes

2024-12-19 12:12 UTC, merged