When `RHEL` publish fails, log reason (`test_results`)
hazelcast/hazelcast-docker pull request #845
Opened 2024-12-24 14:13 UTC by JackPGreen

While investigating an [action failure](https://github.com/hazelcast/hazelcast-docker/actions/runs/12407221911/attempts/1) of an `RHEL` publish failure, the logs indicated that the image had never published, but not _why_.

The publish response includes a link to an `test_results` result which can [provide more information](https://catalog.redhat.com/api/containers/docs/endpoints/RESTGetTestResultsByImageId.html).

Updated the script to log these results in the case of failure.

I've gone backwards and forwards on the implementation - _ideally_ the publish _request_ should be polled rather than the the presence of an image, but would require significant refactoring of the script which is difficult to test due to its destructive nature.
In fact, in isolation this change is pointless - we build from tags so the usage of this change will only gradually increase. But it helps to document _how_ we get investigate subsequent failures. Ideally once next investigated, the root cause can be identified and resolved.

2025-01-06 12:09 UTC, nishaatr requested changes

2025-01-06 12:09 UTC, nishaatr commented on .github/scripts/publish-rhel.sh
> +                TEST_RESULTS=$(curl --silent \
Tested and how?

2025-01-06 12:09 UTC, nishaatr commented on .github/scripts/publish-rhel.sh
> +            echoerr "Test Results:"
Didn't know tests are run during publish. Any ideas what kind of tests?
Thought tests would be run during scanning and not publishing

2025-01-06 12:25 UTC, JackPGreen commented on .github/scripts/publish-rhel.sh
> +            echoerr "Test Results:"
> Didn't know tests are run during publish. Any ideas what kind of tests? Thought tests would be run during scanning and not publishing

I think `tests` would be better thought of as `checks` - for example if you publish an image that references a URL, it checks the URL exists, else the check fails with `404`.

The full list of checks I couldn't say.

2025-01-06 13:09 UTC, nishaatr commented on .github/scripts/publish-rhel.sh
> +            echoerr "Test Results:"
I think what I am trying to get at is that will `.data[]._links.test_results.href'` exists? 
Is it worth checking URL exists before making a `curl` call; otherwise hust skip?

2025-01-06 15:02 UTC, JackPGreen commented on .github/scripts/publish-rhel.sh
> +            echoerr "Test Results:"
> I think what I am trying to get at is that will `.data[]._links.test_results.href'` exists? Is it worth checking URL exists before making a `curl` call; otherwise hust skip?

I think it will, but were in the error state already - the image hasn't published. So if we fail to get the explanation, that's ok too.

2025-01-06 15:06 UTC, nishaatr approved these changes

2025-01-13 09:04 UTC, JackPGreen commented
@ldziedziul are you able to review, please?

2025-01-13 09:08 UTC, ldziedziul approved these changes

2025-01-13 09:08 UTC, merged