Fix `tag_image_push_rhel.yml` for `push` triggers [DI-375]
hazelcast/hazelcast-docker pull request #846
Opened 2024-12-30 11:47 UTC by JackPGreen

In https://github.com/hazelcast/hazelcast-docker/pull/844, the `HZ_VERSION` is computed using the `required` `HZ_VERSION` `input`.

However, this is only `required` for `workflow_dispatch` triggers - it can _also_ be triggered by `push`, where it's instead empty - causing an [action failure](https://github.com/hazelcast/hazelcast-docker/actions/runs/12521044660):
```
Run madhead/semver-utils@latest
Error: Input required and not supplied: version
```

The workflow already derived an appropriate `HZ_VERSION` environment variable by validating the one in the in the `input` - updated to use this instead as it _should_ have done in the first place.

Also simplified the above logic to avoid it overwriting `env.HZ_VERSION` with the same value pointlessly.

Fixes: [DI-375](https://hazelcast.atlassian.net/browse/DI-375)

[DI-375]: https://hazelcast.atlassian.net/browse/DI-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2025-01-06 11:51 UTC, nishaatr requested changes

2025-01-06 11:51 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +          echo "HZ_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
Just checking that this is extracting the version from the tag?

2025-01-06 11:51 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +          version: ${{ env.HZ_VERSION }}
Wondering if `lenient: false` should be set so fails in case version is not formatted properly (when running manually)?

2025-01-06 12:26 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +          echo "HZ_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
From the `ref` - so could be branch (e.g. `master`).
It's existing functionality btw, just refactored.

2025-01-06 12:27 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +          version: ${{ env.HZ_VERSION }}
> Wondering if `lenient: false` should be set so fails in case version is not formatted properly (when running manually)?

We don't need that elsewhere, so 🤞 it's all ok

2025-01-06 13:12 UTC, nishaatr approved these changes

2025-01-13 09:04 UTC, JackPGreen commented
@ldziedziul are you able to review, please?

2025-01-13 09:48 UTC, ldziedziul approved these changes

2025-01-13 09:48 UTC, merged