Di 391
hazelcast/hazelcast-docker pull request #847
Opened 2024-12-30 15:33 UTC by JackPGreen

2025-01-06 13:28 UTC, nishaatr requested changes
Wondering if DRY_RUN is needed simply for testing creds?
I see why this time for testing RHEL v6 container (which is a rare event)
But generally, how often will the credentials change? If they do the build will fail and we can fix. 
The credentials can be tested locally (although I am aware we access AWS creds but thats a proven functionality). Saying this as now we have many IF checks for DRY_RUN and feels little excessive for just checking creds

That said, not too concerned as may be we can use DRY_RUN for other things in the future.

2025-01-06 15:05 UTC, JackPGreen commented on .github/scripts/docker.functions.sh
> +function get_hz_version() {
852c80b39a649bfa4f4b26b47064c3116ab6400a

2025-01-06 15:06 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +  pull_request:
> why `pull_request:`?

To add this to the test suite that's run when you raise a PR

2025-01-06 15:20 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +  pull_request:
You mean run https://github.com/hazelcast/hazelcast-docker/blob/852c80b39a649bfa4f4b26b47064c3116ab6400a/.github/workflows/tag_image_push_rhel.yml#L186?

We don't do this for https://github.com/hazelcast/hazelcast-docker/blob/852c80b39a649bfa4f4b26b47064c3116ab6400a/.github/workflows/tag_image_push.yml (well I don't see `pull_request:`)

Also, DRY_RUN default is `false` so things will happen for PR too?

2025-01-06 15:28 UTC, nishaatr commented
> We aren't just testing credentials - some of the other steps are run too, e.g. deriving HZ_VERSION, checking the yml has valid syntax etc. It's not a great test, but it's something.

Sure but main bulk of functionality is now under DRY_RUN so in reality things might still fail during release

> The first time the build will fail is during a _release_ which is a really bad time to find problems (I don't think we push `SNAPSHOT`, `DEVEL` etc to RHEL).

Yes we don't push DEVEL or SNAPSHOT to RedHat. 
May be we should push for SNAPSHOT like we do for DockerHub so gets tested

2025-01-06 15:33 UTC, JackPGreen commented
> > We aren't just testing credentials - some of the other steps are run too, e.g. deriving HZ_VERSION, checking the yml has valid syntax etc. It's not a great test, but it's something.
> 
> Sure but main bulk of functionality is now under DRY_RUN so in reality things might still fail during release

Yes, that's a risk. This PR closes that gap (a tiny bit).


> Yes we don't push DEVEL or SNAPSHOT to RedHat. May be we should push for SNAPSHOT like we do for DockerHub so gets tested

That would help, as that would give full coverage of _actually publishing_ (missing here) - but it doesn't help validate if someone changes this action.

_Ideally_ you'd find out there's a problem with the action _at the point of changing it_, not some time later when a publish fails.

2025-01-06 15:56 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +  pull_request:
> It doesn't actually have a default - that default value only applies when it's triggered by a workflow_dispatch. Otherwise (e.g. on push or pull_request) it's just blank.

Good to know. thanks 

Prefer we discuss further in stand-up tomorrow as not sure

2025-01-07 10:44 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +  pull_request:
After our conversation, re-implemented.

https://github.com/hazelcast/hazelcast-docker/pull/847/commits/9002162b2a6c37f523d8458837616f3ac9bdfa96

2025-01-07 11:13 UTC, nishaatr requested changes

2025-01-07 11:13 UTC, nishaatr commented on .github/workflows/build-pr.yml
> +      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
May be use `secrets: inherit` rather than passing individual secrets?

2025-01-07 11:13 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +        if: inputs.DRY_RUN != 'true'
nit - may be set `env.DRY_RUN` at the top to force a value (so it caters for empty value in case of non-dispatch event which I presume negation fixes that) and use that `if: inputs.DRY_RUN == 'false'`
Reads better in my head and more deterministic.

2025-01-07 11:26 UTC, JackPGreen commented on .github/workflows/build-pr.yml
> +      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
> May be use `secrets: inherit` rather than passing individual secrets?

I don't think you can do that, if you could I would've done it that way in the other PR.

2025-01-07 11:33 UTC, nishaatr commented on .github/workflows/build-pr.yml
> +      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
I saw [this ](https://docs.github.com/en/enterprise-cloud@latest/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) hence the comment
May be its to do with type of workflow (i.e. reusable vs composite perhaps)

2025-01-14 13:17 UTC, ldziedziul commented on .github/workflows/build-pr.yml
> +      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
> I don't think you can do that, if you could I would've done it that way in the other PR.

@JackPGreen what's the issue with `secretes: inherit` ?

2025-01-14 13:22 UTC, ldziedziul commented on .github/workflows/build-pr.yml
> +      RELEASE_VERSION: ${{ needs.prepare.outputs.LAST_RELEASED_HZ_VERSION_OSS }}
Why explicit `RELEASE_VERSION`? It defaults to HZ_VERSION

2025-01-14 13:22 UTC, ldziedziul commented on .github/workflows/tag_image_push_rhel.yml
> +        if: inputs.DRY_RUN != 'true'
Why not build it without `--push`?

2025-01-15 15:17 UTC, JackPGreen commented on .github/workflows/build-pr.yml
> +      RELEASE_VERSION: ${{ needs.prepare.outputs.LAST_RELEASED_HZ_VERSION_OSS }}
dd9941ef2eadfd0e1d277fd4f81b29df21774ca4

2025-01-15 15:40 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +        if: inputs.DRY_RUN != 'true'
Good idea - d582a62675741dc83e26576bb5f168d3ca3b292d

2025-01-15 16:15 UTC, JackPGreen commented on .github/workflows/build-pr.yml
> +      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
Looks I was wrong - cool!

https://github.com/hazelcast/hazelcast-docker/pull/847/commits/1b3b4fc4710846671edac5ca25dc117f4625f4ec

2025-01-15 17:39 UTC, ldziedziul commented on .github/workflows/tag_image_push.yml
> +          output=
`output` is missleading, maybe `non_dry_run_args` ?

2025-01-15 17:39 UTC, ldziedziul commented on .github/workflows/tag_image_push_rhel.yml
> +        if: inputs.DRY_RUN != 'true'
Great, BTW what issues have you found?

2025-01-15 19:54 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +        if: inputs.DRY_RUN != 'true'
> Great, BTW what issues have you found?

Added to the PR description:

> * fixes ordering issue introduced in [Add RHEL `V6` container support [DI-375] #844](https://github.com/hazelcast/hazelcast-docker/pull/844) where `RHEL_PROJECT_ID` is referenced before it's generated

2025-01-15 19:55 UTC, JackPGreen commented on .github/workflows/tag_image_push.yml
> +          output=
I went with `output` as [that's the setting `--push` actually affects](https://docs.docker.com/reference/cli/docker/buildx/build/#push).

2025-01-20 10:00 UTC, JackPGreen commented
@nishaatr @ldziedziul are you able to review, please?

2025-01-20 11:16 UTC, nishaatr requested changes

2025-01-20 11:16 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +    secrets:
Do we need to list the secrets considering its inherited?
Looks like its needed but just checking

2025-01-20 11:16 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +          if [ "${{ inputs.DRY_RUN }}" == "true" ] ; then
other places I see `if: inputs.DRY_RUN != 'true'` i.e. negated. 
thought might as well keep it consistent

2025-01-20 11:16 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +          output=
may be rename as `args` or `options`
currently its only `--push` but we expect more options otherwise rename to `push`

2025-01-20 11:16 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +          output=
what does `output=` actually do? In Windows this unsets the var but not sure about Bash. May be `output=""`

2025-01-20 11:16 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +        if: inputs.DRY_RUN != 'true'
worth doing this?

2025-01-20 13:38 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +        if: inputs.DRY_RUN != 'true'
> worth doing this?

Personally not a fan as we don't do it elsewhere.

2025-01-20 13:48 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +    secrets:
Good point!

https://github.com/hazelcast/hazelcast-docker/pull/847/commits/1bea658abaaf0086be602bfe2413b6fea114c168

2025-01-20 13:48 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +          output=
Already raised here - https://github.com/hazelcast/hazelcast-docker/pull/847#discussion_r1917085338

2025-01-20 13:49 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +          output=
It's setting a default empty string variable. `=""` might work too but elsewhere we just do `=`.

2025-01-20 14:15 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +          output=
ok. its fine. just looked odd a bit

2025-01-20 14:56 UTC, ldziedziul commented on .github/workflows/tag_image_push_rhel.yml
> +          if [ "${{ inputs.DRY_RUN }}" == "true" ] ; then
Check out the whole block, there's also else part. In other places we run some logic only for non-DRY_RUN, here we run two different things depending on the DRY_RUN flag

2025-01-20 14:56 UTC, ldziedziul approved these changes

2025-01-20 14:58 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +          if [ "${{ inputs.DRY_RUN }}" == "true" ] ; then
> other places I see `if: inputs.DRY_RUN != 'true'` i.e. negated. thought might as well keep it consistent

Not quite sure I follow - do you mean:
- `true` / `!true`
vs
- `true` / `false`
?

2025-01-20 15:04 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +          if [ "${{ inputs.DRY_RUN }}" == "true" ] ; then
I mean like in some steps:

```
      - name: Run preflight scan
        if: inputs.DRY_RUN != 'true'
        run: |
```
And in BASH we do 

`if [ "${{ inputs.DRY_RUN }}" == "true" ] ; then`

I am saying for consistently, lets use `inputs.DRY_RUN != 'true'` and swap the if/else logic

Not a biggy thought

2025-01-20 15:08 UTC, JackPGreen commented on .github/workflows/tag_image_push_rhel.yml
> +          if [ "${{ inputs.DRY_RUN }}" == "true" ] ; then
Sorry I still don't understand - do you have a really specific example?

2025-01-20 15:17 UTC, nishaatr commented on .github/workflows/tag_image_push_rhel.yml
> +          if [ "${{ inputs.DRY_RUN }}" == "true" ] ; then
lets skip. not a biggy :). I will approve

2025-01-20 15:17 UTC, nishaatr approved these changes

2025-01-20 15:18 UTC, merged